### ISSUE TITLE
上报缺失

### ISSUE THREAD

**Issue by tobycroft** [mamoe/mirai-api-http#100]
![image](https://user-images.githubusercontent.com/24893075/83901463-64b48180-a78d-11ea-9ebf-b25ed779832c.png)

目前上报事件里面对“邀请进群”的通知在本地有提示，但是在api接口中是没有提示的，希望修复

**Comment by ryoii** [comment]
#93

**Comment by tobycroft** [comment]
不是啊，这个问题在1.6.5里面没有这个问题，170不可用，在1.7.1里面，群消息这个通知就没了，所以我认为是BUG @ryoii

**Comment by ryoii** [comment]
进群邀请是前几天才加的，我不知道哪来的1.6.5里没有这个问题的说法

**Comment by tobycroft** [comment]
确实是有的，上报会触发一个
![image](https://user-images.githubusercontent.com/24893075/83960492-edc9d680-a8bb-11ea-8701-09fca0d8beac.png)

这样的提示，在171的时候这个提示也没了，很是奇怪

**Comment by ryoii** [comment]
区分入群申请 和 Bot邀请入群申请
这是两个不同的事件

**Comment by tobycroft** [comment]
那么172会更新吗

**Comment by ryoii** [comment]
已经更了
