### ISSUE TITLE
Linux下中文发送乱码

### ISSUE THREAD

**Issue by MicroCBer** [mamoe/mirai-api-http#102]
如题，可否提供一种方式，将要发送的json encodeurl，在httpapi发送时decode 这样就不会乱码，或者使用escape 编码之类的

**Comment by ryoii** [comment]
添加请求头
`Content-Type: application/json;charset=utf8`

**Comment by zhzRedstone** [comment]
同这问题，我添加请求头为
`Content-Type: application/json;charset=GBK`
就不会乱码。。
而`Content-Type: application/json;charset=UTF-8`
会产生类似��的乱码、、

**Comment by Chenwe-i-lin** [comment]
> 同这问题，我添加请求头为
> `Content-Type: application/json;charset=GBK`
> 就不会乱码。。
> 而`Content-Type: application/json;charset=UTF-8`
> 会产生类似��的乱码、、

建议 latest release

**Comment by zhzRedstone** [comment]
> > 同这问题，我添加请求头为
> > `Content-Type: application/json;charset=GBK`
> > 就不会乱码。。
> > 而`Content-Type: application/json;charset=UTF-8`
> > 会产生类似��的乱码、、
> 
> 建议 latest release

好 我试下

**Comment by ryoii** [comment]
> 同这问题，我添加请求头为
> `Content-Type: application/json;charset=GBK`
> 就不会乱码。。
> 而`Content-Type: application/json;charset=UTF-8`
> 会产生类似��的乱码、、
> 

这种情况只能说你的请求就是 GBK 编码的
