### ISSUE TITLE
为不同的账号分开指定authKey

### ISSUE THREAD

**Issue by masnn** [mamoe/mirai-api-http#24]

**Comment by ryoii** [comment]
你可以启动多个console实例

**Comment by masnn** [comment]
启动多个实例一是不方便集中管理，二是会占用较多的内存

**Comment by ryoii** [comment]
我在考虑是否有必要分开指定，这会增加系统的复杂性。
如果您觉得有必要，请简述一下适用的场景

**Comment by liujiahua123123** [comment]
请注意我们不推荐现阶段用mirai进行商业活动

**Comment by liujiahua123123** [comment]
现阶段

**Comment by masnn** [comment]
因为mirai现阶段处于快速流转状态，将多个用户的mirai实例集中化可以更加方便更新/管理

**Comment by masnn** [comment]
不过可能确实没什么人这样用吧（

**Comment by liujiahua123123** [comment]
用户？你为什么都已经说上用户了

**Comment by liujiahua123123** [comment]
你有提供云端挂bot的服务么

**Comment by masnn** [comment]
高中狗表示云服务器都是几人集资一起用的（

**Comment by liujiahua123123** [comment]
... 各挂各的吧 目前不考虑向着方面发展, 一个mirai-console实例内存占用在80-150M左右 应该是足够一人一个的

**Comment by masnn** [comment]
![image](https://user-images.githubusercontent.com/29992205/77824397-59195e80-713d-11ea-91ec-26285e120a8a.png)
（跑
