### ISSUE TITLE
[功能请求] 插件作为 WebSocket 客户端（反向 WebSocket）

### ISSUE THREAD

**Issue by water-lift** [mamoe/mirai-api-http#26]
参照 cqhttp 插件的文档 [通信方式 - CoolQ HTTP API 插件文档](https://cqhttp.cc/docs/4.14/#/CommunicationMethods?id=%E6%8F%92%E4%BB%B6%E4%BD%9C%E4%B8%BA-websocket-%E5%AE%A2%E6%88%B7%E7%AB%AF%EF%BC%88%E5%8F%8D%E5%90%91-websocket%EF%BC%89)

**Comment by ryoii** [comment]
不考虑实现 websocket 客户端，但可以采用 http 上报， #12
