### ISSUE TITLE
C# 使用WebClient调用send<Friend/Group>Message发送中文乱码

### ISSUE THREAD

**Issue by GEEKiDoS** [mamoe/mirai-api-http#3]
已经将WebClient的Encoding属性设置为UTF8并且将ContentType设置为application/json; charset=utf-8, 依旧乱码, 以及尝试过手动编码成字节数组也没用。

接受的数据不乱码

**Comment by ryoii** [comment]
无法复现，检查content-type是否正确设置

**Comment by ryoii** [comment]
我先关闭issue了，还有问题再打开吧
