### ISSUE TITLE
[POST] /command/send 报错

### ISSUE THREAD

**Issue by CharlieJ0hn** [mamoe/mirai-api-http#30]
直接用postman是请使用后台，用python提交是404

**Comment by ryoii** [comment]
请提交详细堆栈错误

**Comment by CharlieJ0hn** [comment]
![image](https://user-images.githubusercontent.com/9925064/78422674-93ca4c00-7693-11ea-9dbd-da673a169c25.png)
就是后台提交怎么办
还有就是ws监听说是没权限

**Comment by ryoii** [comment]
登录命令不支持通过http调用，请在控制台登录。

监听ws请在配置文件中设置全局的enableWebsocket或配置Session级别的enableWebsocket（推荐）。详情浏览文档
