### ISSUE TITLE
关于从/fetchMessage返回的数据格式不统一

### ISSUE THREAD

**Issue by StageGuard** [mamoe/mirai-api-http#32]
当前`/fetchMessage`返回的数据不统一：
若获取成功，返回的是数组`[...]`，若失败，却返回的JSON`{...}`
我觉得应该做到返回数据的格式的统一，以更方便解析并减少解析成本(?)。
如
```json
{
code: 0,
data: [...]
}

```

**Comment by Chenwe-i-lin** [comment]
什么, 又改接口?

**Comment by StageGuard** [comment]
@Chenwe-i-lin 现在不改，等着以后基于http api的封装多了，就不好改了
