### ISSUE TITLE
撤回好友消息返回状态码不正确

### ISSUE THREAD

**Issue by ManiaciaChao** [mamoe/mirai-api-http#34]
### 简介

撤回好友消息返回状态码不符合业务逻辑。

API：`/recall`

可复现：**是**

### 操作步骤

1. 使用`/sendFriendMessage`向任意好友发送消息。
2. 使用`/recall`撤回消息。

### 预期结果

1. 消息成功发送。
2. 消息成功撤回并返回：
```json
{
    "code": 0,
    "msg": "success"
}
```

### 实际结果
1. 消息成功发送。
2. 消息成功撤回并返回：
```json
{
    "code": 20,
    "msg": "Bot被禁言"
}
```

**Comment by ryoii** [comment]
请提供一下`core`的版本号

**Comment by ManiaciaChao** [comment]
> 请提供一下`core`的版本号

`mirai-console` v0.4.2，`core`是0.33.0。

**Comment by ryoii** [comment]
已处理，但当前 `core` 确实可能出现好友消息撤回失败的问题
