### ISSUE TITLE
V1.5.1 Core0.34.0 Console 0.4.6 造成机器人卡死？

### ISSUE THREAD

**Issue by zhzRedstone** [mamoe/mirai-api-http#38]
我使用自动登录插件和该插件，在启动要登录时卡死
[Core 0.34.0 Console 0.4.6使用该插件在登录时卡死](https://github.com/ryoii/mirai-console-addition/issues/5)

**Comment by ryoii** [comment]
暂时关闭issue，若新版本 `console` 无法解决再 reopen
