### ISSUE TITLE
无法接收引用消息

### ISSUE THREAD

**Issue by sgalal** [mamoe/mirai-api-http#43]
![引用消息的示意图](https://user-images.githubusercontent.com/32255369/78756470-6f30e580-79ad-11ea-89da-5e9dec4a276b.png)

**预期**

如[文档](https://github.com/mamoe/mirai-api-http/blob/master/MessageType.md#quote)中所述，格式为：

```python
{
    "type": "Quote",
    "id": 123456,
    "groupId": 123456789,
    "senderId": 987654321,
    "targetId": 9876543210,
    "origin": [
        { "type": "Plain", text: "text" }
    ] 
}
```

**实际**

```python
{'code': 5, 'msg': '指定对象不存在'}
```

**Comment by ryoii** [comment]
请问您是否在构建 `Quote` 对象

**Comment by Chenwe-i-lin** [comment]
直接指定 quote, 指向你要回复的消息的 MessageID 即可.

**Comment by sgalal** [comment]
不是，这是 **GET** 请求 `/fetchMessage?sessionKey=YourSessionKey&count=10` 的结果

**Comment by ryoii** [comment]
> 不是，我是试图接收消息。这是 **GET** 请求 `/fetchMessage?sessionKey=YourSessionKey&count=10` 的结果

1. 是否是接受所有 `Quoto` 消息都会出现这个问题
2. `console` 控制台有无报错信息
3. `Quoto` 的原消息是否曾经有被bot接收过

**Comment by sgalal** [comment]
昨天及今天上午不行，现在可以了
