### ISSUE TITLE
[功能请求] docker镜像

### ISSUE THREAD

**Issue by water-lift** [mamoe/mirai-api-http#45]
rt

好处：
1. 无需java环境
2. 方便挂在后台运行
3. 内置适配当前版本的mirai-console，避免冲突

**Comment by water-lift** [comment]
（参照：https://cqhttp.cc/docs/4.14/#/Docker

**Comment by masnn** [comment]
我来吧

**Comment by daofeng2015** [comment]
> rt
> 
> 好处：
> 
> 1. 无需java环境
> 2. 方便挂在后台运行
> 3. 内置适配当前版本的mirai-console，避免冲突

现在是快速流转的版本..docker版本要是出了问题不好判断的..再说这个就是调用java运行jar文件.很简单的

**Comment by masnn** [comment]
```
apt-get install openjdk-8
curl xxx >./mirai_console_wrapper.jar
java -jar ./mirai_console_wrapper.jar
```

**Comment by masnn** [comment]
cq那个还要配vnc+wine很麻烦所以搞了个镜像

**Comment by water-lift** [comment]
> cq那个还要配vnc+wine很麻烦所以搞了个镜像

emm, qs

主要还是个人用docker用习惯了（x

**Comment by ryoii** [comment]
功能可以有，但这不是 `api-http` 的功能范围

另外，稳定版前不建议固定 `console` 的版本。一是安全性问题，二是 `api-http` 目前随 `console` 更新，固定版本的 `console` 导致插件也不能正常执行。

**Comment by pyg2007** [comment]
cq是wine跟novnc配置麻烦，mirai直接就能运行，有何意义？
