### ISSUE TITLE
[新功能请求] 群事件是否考虑增加 群组解散事件？

### ISSUE THREAD

**Issue by RF-Tar-Railt** [mamoe/mirai-api-http#585]
即 BotLeaveEvent.Disband, 机器人因群主解散群而退出群， 操作人一定是群主

**Comment by RF-Tar-Railt** [comment]
![图片](https://user-images.githubusercontent.com/42648639/175905656-0519008b-39ff-4b19-a7ce-e6390141ab68.png)

**Comment by ryoii** [comment]
已经有PR提交了，但是 CI 似乎失败了。我测试没问题后，将作为下个版本的 feature 发布
