### ISSUE TITLE
将jar放入mirai console的plugins文件夹后,再次运行产生错误

### ISSUE THREAD

**Issue by wazedxwxx** [mamoe/mirai-api-http#6]
出现\login后,下面报错
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
系统为Centos7
javac 11.0.6

**Comment by wazedxwxx** [comment]
忘了编辑yml文件

**Comment by ryoii** [comment]
此为warning，不影响使用。报错应该是其他原因
