### ISSUE TITLE
SendGroupMessage 返回数据为 sequenceId not yet available

### ISSUE THREAD

**Issue by cyanray** [mamoe/mirai-api-http#66]
请求地址: http://127.0.0.1:789/sendGroupMessage
请求内容: 
`{"messageChain":[{"text":"你今天共有 ","type":"Plain"},{"text":"3","type":"Plain"},{"text":" 节课\n","type":"Plain"},{"text":"1","type":"Plain"},{"text":". ","type":"Plain"},{"text":"船舶材料力学","type":"Plain"},{"text":"，","type":"Plain"},{"text":"A01 - 330","type":"Plain"},{"text":"，","type":"Plain"},{"text":"8:20 - 10:00","type":"Plain"},{"text":"\n","type":"Plain"},{"text":"2","type":"Plain"},{"text":". ","type":"Plain"},{"text":"大学英语拓展课程（Ⅱ）","type":"Plain"},{"text":"，","type":"Plain"},{"text":"A01 - 317","type":"Plain"},{"text":"，","type":"Plain"},{"text":"14:00 - 15:40","type":"Plain"},{"text":"\n","type":"Plain"},{"text":"3","type":"Plain"},{"text":". ","type":"Plain"},{"text":"船舶静力学","type":"Plain"},{"text":"，","type":"Plain"},{"text":"A01 - 118","type":"Plain"},{"text":"，","type":"Plain"},{"text":"16:00 - 17:40","type":"Plain"},{"text":"\n","type":"Plain"}],"sessionKey":"QmfivD1A","target":1029259687}`
返回数据: `sequenceId not yet available`

虽然返回数据是`sequenceId not yet available`，但是QQ群能收到消息（消息成功发出去了）。
在调用SendTempMessage时有同样的返回值，但是临时消息没有成功发出去，对方收不到。
在调用SendFriendMessage时没有错误。

修改建议：出错之后返回的数据还是 json 格式，把错误放到 msg 里。

版本信息: 
mirai v0.35.7 
mirai-http-api v1.6.3

**Comment by ryoii** [comment]
HTTP状态码返回500标识服务器发生意料之外的异常，这种情况下为什么还期望要返回json格式的数据？

**Comment by cyanray** [comment]
> HTTP状态码返回500标识服务器发生意料之外的异常，这种情况下为什么还期望要返回json格式的数据？

这个看习惯吧。我习惯只用一种数据结构，比如只用JSON，即使是非200状态。
不做这个修改的话，我另外做适配就好了。

**Comment by damaoooo** [comment]
巧了我也遇上这种情况了，无限死循环，发送很多消息，`mirai-http-api`返回了一堆报错，导致`python-mirai`认为连接失效，于是重新发送，于是无限套娃，在sendGroupMessage铁定报错，sendFriendMessage不报错

**Comment by ryoii** [comment]
> 巧了我也遇上这种情况了，无限死循环，发送很多消息，`mirai-http-api`返回了一堆报错，导致`python-mirai`认为连接失效，于是重新发送，于是无限套娃，在sendGroupMessage铁定报错，sendFriendMessage不报错

一个框架对于自身无法处理的异常，应当向上抛出，而不是通过一种理所当然的方式自行处理然后隐藏异常。这里同理，我认为对于500这种错误，需要的是通知调用者发生了什么事情，而不是直接重试。

**Comment by Chenwe-i-lin** [comment]
> > 巧了我也遇上这种情况了，无限死循环，发送很多消息，`mirai-http-api`返回了一堆报错，导致`python-mirai`认为连接失效，于是重新发送，于是无限套娃，在sendGroupMessage铁定报错，sendFriendMessage不报错
> 
> 一个框架对于自身无法处理的异常，应当向上抛出，而不是通过一种理所当然的方式自行处理然后隐藏异常。这里同理，我认为对于500这种错误，需要的是通知调用者发生了什么事情，而不是直接重试。

python-mirai 将在下一个版本中对此情况进行优化, 虽然我个人由于学业原因已经无法正常更新了...

**Comment by Chenwe-i-lin** [comment]
........我必把 ptilopsis 的 merge_fix 搬到这里来专治你们这种生成一堆 Plain 的...
