### ISSUE TITLE
上传图片，产生了一些错误的情况

### ISSUE THREAD

**Issue by InPRTx** [mamoe/mirai-api-http#67]
如图。当UnifiedMessageRelay使用后端的
mirai-api-http，上传图片之后，产生了一个QQ号为0的url
http://c2cpicdw.qpic.cn/offpic_new/0//18446744072377537249-3806766343-9CD1ED5914FFB6E3A6A77E8CA7253235/0
![image](https://user-images.githubusercontent.com/56180468/79949091-8f7d9b80-84a7-11ea-906f-fadb4075b011.png)
原始问题地址：
https://github.com/JQ-Networks/UnifiedMessageRelay/issues/73

**Comment by ryoii** [comment]
综合原问题的情况已经了解。
1. 由bot发送的图片服务器不会返回图片的url，现在的url是通过计算出来的
2. QQ近期对好友图片的url规则做出了修改，构造规则尚未完全清楚

好友图片目前存在两种规则，一种是`/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`(8+4+4+4+12)的格式，另一种是问题描述的。

最后，QQ号为0是由于url是构造出来导致的，并不影响图片访问。
