### ISSUE TITLE
群名修改事件的opertor一直是null

### ISSUE THREAD

**Issue by 940842546** [mamoe/mirai-api-http#73]
mirai-api-http-v1.6.4.jar

**Comment by 940842546** [comment]
mirai-console-wrapper-0.3.0.jar

**Comment by 940842546** [comment]
用的是这两个

**Comment by 940842546** [comment]
好叭是 群名片改动 MemberCardChangeEvent
不是群名 这个api是腾讯做了限制吗

**Comment by ryoii** [comment]
是的，无法获取具体修改的人是谁。
目前都认为是bot自己改的。
