### ISSUE TITLE
使用 serviceMessage，弃用 xml json app message

### ISSUE THREAD

**Issue by jqqqqqqqqqq** [mamoe/mirai-api-http#76]
Core 0.39.5
Console 0.4.11
MiraiAPIHTTP version v1.6.3

遇到了以下问题 [You promised me JSON but sent XML](https://www.youtube.com/watch?v=nSKp2StlS6s&app=desktop)
<img width="677" alt="image" src="https://user-images.githubusercontent.com/12872927/80560039-890e8880-89ad-11ea-9591-c8d9a87f32da.png">

复现方法：使用iOS Safari分享github首页到qq

serviceMessage类不区分具体是json/app/xml，兼容性更好，希望替换接口为service

**Comment by ryoii** [comment]
不要急，core刚发布，下版本再适配。
