### ISSUE TITLE
[建议]希望可以将机器人与机器人区分开

### ISSUE THREAD

**Issue by tobycroft** [mamoe/mirai-api-http#88]
目前的话
![image](https://user-images.githubusercontent.com/24893075/82531441-00c97080-9b72-11ea-8290-0b7de423ac5d.png)

例如这样的加群信息，我看了header，header里面只能定义一个请求头，没把饭定义多个请求头，这个就很麻烦了，不知道后续版本，能不能在回馈的信息里面直接带上bot的号码，这样才能便于识别

**Comment by ryoii** [comment]
上报接口?

**Comment by tobycroft** [comment]
是的，就是上报接口的内容，因为不存在verify的session绑定动作，所以……没办法从上报消息里面得知是从哪个QQ号码上传上来的

**Comment by tobycroft** [comment]
@ryoii 对对返回信息里面带上本账号这样的

**Comment by tobycroft** [comment]
Emm.....还没有更新啊……
