### ISSUE TITLE
[Feature Request] Support to specify listening address

### ISSUE THREAD

**Issue by lideming** [mamoe/mirai-api-http#89]
Hi,
I want the http server to listen on a loopback address like 127.0.0.233, then I can use Caddy to setup reverse proxy for it.

**Comment by ryoii** [comment]
Is it listening `0.0.0.0`? I am not sure. Could you check it for me.

**Comment by lideming** [comment]
Yes, it is. It currently listen on 0.0.0.0 (i.e. every available IPv4 addresses on the system). But I want it to listen on a specific address only.
