### ISSUE TITLE
Release该更新了……

### ISSUE THREAD

**Issue by tobycroft** [mamoe/mirai-api-http#91]
上次的那个http反向的问题，要回退1.6.5才能解决……这个问题我看已经修复了，但是因为没有发realese所以下载不到新的jar啊

**Comment by ryoii** [comment]
1.7.0的上报应该指示配置文件读错了，不影响启动。
新版本在最近加上新功能后一并发布

**Comment by tobycroft** [comment]
@ryoii 但是这样的话我没办法使用上报功能啊

**Comment by tobycroft** [comment]
因为我是依赖反向http的，所以如果不能使用上报功能的话，我的整个程序就无法运行了额……

**Comment by ryoii** [comment]
那你要使用1.6.5版本对应的core和console版本

**Comment by tobycroft** [comment]
ahh……这台复杂了，我想问下新版什么时候更新呢？

**Comment by ryoii** [comment]
快的话今晚，慢的话周末

**Comment by tobycroft** [comment]
上周没等到=。=

**Comment by ryoii** [comment]
`core`修改了一个内部接口，导致编译不能。

而且鸽子的本质就是鸽子

**Comment by tobycroft** [comment]
那咋办哦

**Comment by tobycroft** [comment]
那不然先把我之前的提的issue顺便解决了？回报的时候加一个当前QQ的信息这样的

**Comment by tobycroft** [comment]
有没有办法解决的呢

**Comment by ryoii** [comment]
等`core`先更新吧，不然修复了也没法跑在最新的`core`上

**Comment by tobycroft** [comment]
我觉得是不是应该将这个问题transfer到core那边去

**Comment by ryoii** [comment]
已经写好了，等`core`的1.1.0更新即可
