### ISSUE TITLE
上报服务启动失败

### ISSUE THREAD

**Issue by MatchaC** [mamoe/mirai-api-http#94]
setting.yml配置如下
![图片](https://user-images.githubusercontent.com/45539918/83007504-61f7b500-a046-11ea-97e1-c0f9f040fe18.png)
已配置report.enable=true但依旧启动失败
![图片](https://user-images.githubusercontent.com/45539918/83007814-c7e43c80-a046-11ea-9647-797e6e878a3f.png)

**Comment by ryoii** [comment]
#91 fixed
