### ISSUE TITLE
API /uploadImage doesn't work in a right way.  Broken pipe (Write failed)!

### ISSUE THREAD

**Issue by zhaxzhax** [mamoe/mirai-api-http#95]
![QQ截图20200515095647](https://user-images.githubusercontent.com/44116759/83098524-7f2b9280-a0dd-11ea-8cec-d6e307072557.png)
The problem as shown in the picture. Wondering what happened in mirai-api-http excute process.
![QQ图片20200528121952](https://user-images.githubusercontent.com/44116759/83099147-1ba26480-a0df-11ea-8e78-95e38ce4a67f.png)
This is my images folder.
It is can be seen that the file has already been transferred to mirai-api-http server.
Thanks for help.

**Comment by ryoii** [comment]
#85 same case

**Comment by zhaxzhax** [comment]
Thanks. I will just close this issue. Everyone with the same problem could go on #85
