### ISSUE TITLE
【Feture Request】 能否增加 websocket 支持？

### ISSUE THREAD

**Issue by pandolia** [mamoe/mirai-api-http#96]
能否增加 websocket 支持，消息等事件通过 websocket 发送到客户端（浏览器）。如果按现在的事件上报模式的话，在浏览器中开发 mirai 不太方便。

**Comment by ryoii** [comment]
浏览器端不是应该使用正向的WebSocket么，对于正向的WebSocket是支持的。

**Comment by pandolia** [comment]
哦，看到文档了，谢谢！
