### ISSUE TITLE
上报服务无法收到TempMessage

### ISSUE THREAD

**Issue by MatchaC** [mamoe/mirai-api-http#97]
v1.7.1
群消息和好友消息正常

另外有个偶发性的情况
![图片](https://user-images.githubusercontent.com/45539918/83300965-7ba62180-a22b-11ea-980c-0fdb30fe8e38.png)
有时候群消息会有2个sender字段，中间那种sender以前没见过

**Comment by ryoii** [comment]
我觉得吧，是你请求客户端出bug了。因为第二个sender显然不符合json格式，是个缝合怪

**Comment by MatchaC** [comment]
> 
> 
> 我觉得吧，是你请求客户端出bug了。因为第二个sender显然不符合json格式，是个缝合怪

这个不是我请求的，是上报服务推送的，我没有做任何其他操作直接打印了Body的内容

**Comment by MatchaC** [comment]
> 
> 
> 我觉得吧，是你请求客户端出bug了。因为第二个sender显然不符合json格式，是个缝合怪

主要是TempMessage收不到

**Comment by ryoii** [comment]
At 不存在的人会解析为文本消息，TempMessage下个版本添加吧
